/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 computer.gltf 
Author: NobleCrow (https://sketchfab.com/NobleCrow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-old-pc-7d8881260cce4de39fc8fbc01ab47929
Title: Low Poly Old PC
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./computer.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[-2.172, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} position={[-2.358, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} position={[1.071, 0, 0]} scale={0.882} />
    </group>
  )
}

useGLTF.preload('/computer.gltf')
