/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 room.gltf 
Author: IsaacTheMaverick (https://sketchfab.com/IsaacTheMaverick)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-room-a6bf7976f3ac401e96907aa5b8a0c1c1
Title: Low Poly Room
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./room.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-126.857, 16.425, 29.041]} rotation={[-Math.PI / 2, 0, 0]} scale={16.095}>
        <mesh geometry={nodes.Cube002_UberTexture_0.geometry} material={materials.UberTexture} />
        <mesh geometry={nodes.Cube002_PC_Glass_0.geometry} material={materials.PC_Glass} />
        <mesh geometry={nodes.Cube002_Floor_0.geometry} material={materials.Floor} />
      </group>
    </group>
  )
}

useGLTF.preload('/room.gltf')
